// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCxLADjT3pPUWycJAlp3Ljf8gzp32i-OY',
    appId: '1:91760374638:web:e3a430c0dc4f4f5b05877f',
    messagingSenderId: '91760374638',
    projectId: 'code-buddy-cda81',
    authDomain: 'code-buddy-cda81.firebaseapp.com',
    storageBucket: 'code-buddy-cda81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4N6m6_ljSWFTnWfER1CUX1wSiaYfCvw',
    appId: '1:91760374638:android:c8dc4490f6de201c05877f',
    messagingSenderId: '91760374638',
    projectId: 'code-buddy-cda81',
    storageBucket: 'code-buddy-cda81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3hGG5-xRrWITCnmpSXz-Bo0idm8vKmE',
    appId: '1:91760374638:ios:9d0db975a7f89a1305877f',
    messagingSenderId: '91760374638',
    projectId: 'code-buddy-cda81',
    storageBucket: 'code-buddy-cda81.firebasestorage.app',
    iosBundleId: 'com.example.acex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs3hGG5-xRrWITCnmpSXz-Bo0idm8vKmE',
    appId: '1:91760374638:ios:9d0db975a7f89a1305877f',
    messagingSenderId: '91760374638',
    projectId: 'code-buddy-cda81',
    storageBucket: 'code-buddy-cda81.firebasestorage.app',
    iosBundleId: 'com.example.acex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCxLADjT3pPUWycJAlp3Ljf8gzp32i-OY',
    appId: '1:91760374638:web:9787439c9ea886d405877f',
    messagingSenderId: '91760374638',
    projectId: 'code-buddy-cda81',
    authDomain: 'code-buddy-cda81.firebaseapp.com',
    storageBucket: 'code-buddy-cda81.firebasestorage.app',
  );
}
